config/routes.rb
Rails.application.routes.draw do


  get 'password_resets/new'
  get 'password_resets/edit'

  root 'sessions#new'
  get   '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post   '/users/search', to: 'users#search'
  get   '/users/search', to: 'users#search'
  get   '/users/nick', to: 'users#check_username'
  get 'notifications' , to: 'notifications#index'

  resources :items
  get 'items/:f',  to: 'items#index'
  get 'items/:id/return' ,  to: 'items#return' , as: :item_return
  resources :users
 	resources :account_activations, only: [:edit] 
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord

  #todo create user soft delete feature
  attr_accessor :remember_token, :activation_token, :reset_token
  has_many :owned_items, :class_name => 'Item', :foreign_key =>  :owner_id
  has_many :received_items, :class_name => 'Item', :foreign_key => :recipient_id
  has_one :info, :class_name => 'UserInfo' , :foreign_key =>  :user_id
  accepts_nested_attributes_for :info

  has_many :sent_notifications, :class_name => 'Notification', :foreign_key =>  :sender_id
  has_many :received_notifications, :class_name => 'Notification', :foreign_key => :to_id


	before_save :downcase_email if :user_type
	before_create :create_activation_digest
	validates :name, presence: true , length: { maximum: 50 }

  validates :nick, presence: true , length: { minimum: 4 , maximum: 15 } if :user_type

	validates :email, presence: true,
                    allow_blank: false , 
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 50 }  if :user_type
	validates :email,   format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i } if :user_type

	has_secure_password           
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true 


  attr_accessor :messages_unseen

	# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest") #send to self
  	return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 24.hours.ago
  end

  def set_updated_password
    update_attribute(:updated_since_sent, true)
  end

  def self.search(search)
    @users = select('name, nick').where('nick LIKE ?', "#{search}%")
  end

  def self.username_available(username)
    User.where(nick: username).empty?
  end




  private
    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

    def user_type
      self.class.name == "User"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "login", except: [:index, :show, :edit, :update]	

  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def new
    if logged_in?
      redirect_to @current_user  
      return
    end 
    @user = User.new
    render layout: "login" 
  end

  def show
    return @user = User.find(params[:id]) if current_user.id.to_s == params[:id]
    if Item.are_users_related?(current_user.id,params[:id])
      @user = User.find(params[:id])
    else
      flash[:warning] = "Can't see unrelated people profiles!"
      redirect_to items_path
    end
  end

  def login
  	#render layout: "login"
  end

  def create
    @user = User.new(user_params)  
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.where(activated: true).paginate(page: params[:page], :per_page => 5)
  end 

  def update
    
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def search
    @users = User.search(params[:search_text]) if !params[:search_text].blank?
    respond_to do |format|
      format.json { render :json => @users  }
    end
  end

  def check_username
    available = User.username_available(params[:username])
    respond_to do |format|
      format.json { render :json => available  }
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, info_attributes: [:id, :phone_number])
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
  	return nil if !user.id
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end



end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="col-xs-10 col-md-12 col-lg-12">
    

    <div class="page-header">
      <h1><%= yield(:title)%></h1>
    </div> 

    <%= render 'shared/error_messages', object: @user %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label "Username" %>
    <%= f.email_field :nick, class: 'form-control' %> 

    <p><span class="username-status"></span></p>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <% if params[:action] == 'edit' %>
      <div class="gravatar_edit">
          <%= gravatar_for @user %>
          <a href="http://gravatar.com/emails" rel="noopener" target="_blank">change</a>
      </div>
    <% end %>

  </div>
  <% if params[:action] != 'new' %>
  <div class="col-xs-6 ">

    <div class="page-header">
      <h1><%= t(:contact_info) %></h1>
    </div>

      <%= f.fields_for :info do |ff|  %>

        <%= ff.label :phone_number %>
        <%= ff.text_field :phone_number, class: 'form-control' %>

        <%= ff.label :address %>
        <%= ff.text_field :address, class: 'form-control' %>

        <%= ff.label :contact_email %>
        <%= ff.text_field :contact_email, class: 'form-control' %>

      <% end %>

  </div>
   <% end %>
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-edit-user" %>
<% end %>

<script>

 $(function () {
        $('#user_nick').focusout(function(e){
          nick = $(e.currentTarget).val();
          if (nick == '') {
            $('.username-status').html("");
            return false}
          url = '/users/nick';
          $.ajax({
              url: url,
              dataType: 'json',
              data: {
                'username': nick
              },
              success: function(data) {
                if(data){
                  $('.username-status').html("Username Available!");
                  //add styling
                }
                else{
                  $('.username-status').html("Username already taken");
                   //add styling
                }
              }
          })
        });
      });

</script>

app/views/users/_user-option-list.html.erb
<option value="<%= user.email %>"><%= user.name.titleize %></option>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:button_text,  t(:update) ) %>
<% provide(:title, t(:edit) ) %>


<%= render 'form' %>

app/views/users/index.html.erb
<h1>All users</h1>
<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>

<div class="signup-form">
	<div class="row">
	  <div class="col-md-6 col-md-offset-3">
	        <%= render 'form' %>
	  </div>
	</div>
	<div class="log-sign-switch row"><%= link_to "<button>Already a user? Log in</button>".html_safe, login_path, :id => "go-signup" %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="container-fluid">
        <!-- Page Heading -->
    <div class="row">
       	<div class="col-lg-12">


<% if current_user.id.to_s == params[:id] %>
	<div class="page-header">
	    <h1><%= t(:personal_info) %>  <span><%= link_to t(:edit) + " Info", edit_user_path(@user) , :class => "btn btn-success" %></span></h1>
	</div>
	<div>
		<%= gravatar_for @user %>
	  <p><%= t(".name") %>: <%= @user.name %></p>
	  <p><%= t(".username") %>: <%= @user.nick %></p>
	  <p><%= t(".joined_in") %> <%= @user.created_at.to_s %></p>
	</div>
<% end %>


<div class="page-header">
    <h1><%= t(:contact_info) %></h1>
</div>
<div>

	<p><%= t(".name") %>: <%= @user.name %></p>
	<p><%= t(".username") %>: <%= @user.nick %></p>
	<p><%= t(".phone") %>: <%= @user.info.phone_number if @user.info%> <p>

</div>


		</div>
	</div>
</div>