config/routes.rb
Rails.application.routes.draw do


  get 'password_resets/new'
  get 'password_resets/edit'

  root 'sessions#new'
  get   '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post   '/users/search', to: 'users#search'
  get   '/users/search', to: 'users#search'
  get   '/users/nick', to: 'users#check_username'
  get 'notifications' , to: 'notifications#index'

  resources :items
  get 'items/:f',  to: 'items#index'
  get 'items/:id/return' ,  to: 'items#return' , as: :item_return
  resources :users
 	resources :account_activations, only: [:edit] 
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html"><%= t :site_title %></a>
    </div>
    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
                        <li class="dropdown notifications">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b> <span class="badge badge-notify"><%= session[:messages_size] if session[:messages_size] and session[:messages_size] != 0 %></span> </a>
                    <ul class="dropdown-menu message-dropdown">
                        <%= render partial: "notifications/nav_notification" , collection: get_notifications(@current_user)  || "There's no notifications to be displayed", as: :notification %>
                        <li class="message-footer">
                            <%= link_to "Read All Notifications",notifications_path %>
                        </li>
                    </ul>

                </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-user"></i> <%= @current_user.name %><b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to t(:profile),current_user %>
                </li>
                <li>
                    <a href="#"><%= link_to t(:edit),edit_user_path(current_user) %></a>
                </li>
                <li class="divider"></li>
                <li>
                    <%= link_to  logout_path, "method" => "delete" do %>
                      <i class="fa fa-fw fa-power-off"></i> <%= t :log_out %> 
                    <%end%>

                </li>
            </ul>
        </li>
    </ul>
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">


        <ul class="nav navbar-nav side-nav">
        	 <!-- <li class="bolado">
        	 	<div class="my-img-container">
        	    <%= image_tag("omar.jpg" , class: "user-photo") %>
        	 	</div is>
    			<span class="user-name" ><a href="">Omar Ramalho</a></span>	
            </li> -->

            <li class=<%= 'active' if params[:f] == 'all' %>>
                <%= link_to items_path(:f => "all") do %>
                  <i class="fa fa-fw fa-dashboard"></i> <%= t :all %> 
                <% end %>
            </li>
            <li class=<%= 'active' if params[:f] == 'mine' %>>
              <%= link_to  items_path(:f => "mine") do %>
                <i class="fa fa-fw fa-bar-chart-o"></i> <%= t :mine_menu %> 
              <% end %>
           </li>
             <li class=<%= 'active' if params[:f] == 'others' %>>
                 <%= link_to  items_path(:f => "others") do %>
                   <i class="fa fa-fw fa-bar-chart-o"></i> <%= t :others_menu %> 
                 <% end %>
            </li>
            <li class=<%= 'active' if params[:f] == 'others' %>>
                 <%= link_to  items_path(:f => "done") do %>
                   <i class="fa fa-fw fa-bar-chart-o"></i> <%= t :returned_menu %> 
                 <% end %>
            </li>
            <li>
                <%= link_to  notifications_path do %>
                  <i class="fa fa-fw fa-group"></i> <%= t :notifications %> 
                <%end%>
            </li>
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</nav>

app/views/shared/_page_header.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            <%= t :site_title %> <small><%= t :site_subtitle %></small>
        </h1>
    </div>
</div>