config/routes.rb
Rails.application.routes.draw do


  get 'password_resets/new'
  get 'password_resets/edit'

  root 'sessions#new'
  get   '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post   '/users/search', to: 'users#search'
  get   '/users/search', to: 'users#search'
  get   '/users/nick', to: 'users#check_username'
  get 'notifications' , to: 'notifications#index'

  resources :items
  get 'items/:f',  to: 'items#index'
  get 'items/:id/return' ,  to: 'items#return' , as: :item_return
  resources :users
 	resources :account_activations, only: [:edit] 
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
end

app/models/item.rb
class Item < ApplicationRecord
 
	belongs_to :owner,  :class_name => "User" , foreign_key: "owner_id"
    belongs_to :recipient, :class_name => "User" , foreign_key: "recipient_id"
    validates  :name, presence: true, length: { minimum: 4, maximum: 30 }
    validates  :date_lended, presence: true
    validates  :initial_return_date, presence: true
    validate   :is_range_ok?

    after_update :crop_image

	attr_accessor :image
    mount_uploader :image , ImageUploader

    # has_attached_file :image, styles: { large: "300x300>", thumb: "150x150>" }, default_url: "/images/:style/missing.png"
  	# validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  	# validates_attachment_file_name :image, matches: [/png\z/, /jpe?g\z/, /gif\z/]


    scope :open, -> { where(returned: false) }
	scope :closed, -> { where(returned: true) }

	

	attr_accessor :guest_recipient,:recipient_email,:is_guest,:guest_phone, :guest_address,:guest_email
	
	attr_accessor :crop_x, :crop_y, :crop_w, :crop_h


	def Item.all_with_flag(user,flag)
		case flag
		when 'mine'
		  items = user.owned_items.open
		when 'others'
		  items = user.received_items.open
		when 'done'
		  items = Item.where(owner_id: user.id).closed
		else
  		  items = Item.all.open
		end

		decorators = ItemDecorator.build_collection(items)
	end

	def is_range_ok?
	    if date_lended.to_s > initial_return_date.to_s
	      errors.add(:initial_return_date, 'must be before lended')
	    end
	    if date_lended.to_s > Date.current.to_s
	      errors.add(:date_lended, 'must be in the past')
	    end
    end

    def is_owned_by?(user)
      self.owner_id == user.id	
    end

	#Could be PORO?
    def Item.are_users_related?(current, to_display)
    	!Item.where(owner_id: current, recipient_id: to_display).or(Item.where(owner_id: to_display ,recipient_id: current)).select(:id).first().nil?
    end

	def crop_image
		image.recreate_versions! if crop_x.present?	
	end



	def Item.prepare_for_save(item_params,owner)
	  @item = Item.new(item_params)
	  @item.owner_id = owner.id
	  if item_params[:is_guest] == "1"
		unless item_params[:guest_recipient].blank?
		  guest = GuestUser.create(name: item_params[:guest_recipient], email: nil , password:"gimmebackdefault")
		  uf = UserInfo.create(phone_number: item_params[:guest_phone], contact_email: item_params[:guest_email], address: item_params[:guest_address], user_id: guest.id)
		  @item.recipient_id = guest.id
		else
		   @item.errors.add(:recipient,"Guest Recipient needs a name")
		end
	  elsif  item_params[:is_guest] == "0"
	  	
	  	if r = User.find_by(nick: item_params[:recipient_email])
 		  @item.recipient_id = r.id
 		else
 		   @item.errors.add(:recipient,"Recipient email not found!")
	  	end
	  end
	  @item
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  layout "model-edit", only: [ :edit,:new ,:show]  
  before_action :set_locale

  # GET /items
  # GET /items.json
  def index
    @items_decorators = Item.all_with_flag(@current_user,params[:f])
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item_decorator = ItemDecorator.new(@item)
  end 

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    item = Item.find(params[:id])
    session[:return_to] ||= request.referer
    if !item.is_owned_by?(current_user)
      flash[:error] = "Could not edit item that isnt yours"
      redirect_to session.delete(:return_to)
    end
  end

  # POST /items
  # POST /items.json
  def create
    #need preparation and saving of GuestUser if its the case
    @item = Item.prepare_for_save(item_params,@current_user)
    respond_to do |format|
      if @item.save
        if params[:item][:image].present?
          Notification.send_notification(@item, :create)
          format.html { render :crop }
        else
          format.html { redirect_to @item, notice: 'Item was successfully created.' }
          format.json { render :show, status: :created, location: @item }
        end
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update 
    #byebug
    respond_to do |format|
      if @item.update!(item_params)
        if params[:item][:image].present?
          format.html {render :crop , notice: 'Now, crop your image.' }
        else
          format.html { redirect_to @item, notice: 'Item was successfully updated.' }
          format.json { render :show, status: :ok, location: @item }
        end
      else
        flash[:error] = "Couldnt update"
        flash[:model] = @item
        flash[:model_errors] = @item.errors
        format.html { redirect_to :action => :edit }      
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def format_date(item)
     #l(item.date_lended.to_date)
  end

  def return
    @item = Item.find(params[:id])
    if !@item.is_owned_by?(@current_user)
      flash[:error] = "Could not returned that item"
      redirect_to items_url
    end
    if @item.update_columns(returned_date: Date.current,returned: true)
      Notification.send_notification(@item, :ret)
      flash[:success] = "Item returned successfully! Check history list to see it"
    else
      flash[:error] = "Could not return item."
    end
    redirect_to items_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      if flash[:model]
        @item = Item.find(flash[:model]["id"])
        @item.assign_attributes(flash[:model])
        flash[:model_errors].each do |k,v|
          @item.errors.add(k,v[0])
        end
        @item.date_lended =  I18n.localize @item.date_lended if @item.date_lended
        @item.initial_return_date = I18n.localize @item.initial_return_date if @item.initial_return_date  
        flash.clear
        @item
      else
        @item = Item.find(params[:id])
        @item.date_lended =  I18n.localize @item.date_lended if @item.date_lended
        @item.initial_return_date = I18n.localize @item.initial_return_date if @item.initial_return_date  
      end

     
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :date_lended, :initial_return_date, :recipient_email, :is_guest ,:guest_recipient, :guest_phone , :image, :crop_x, :crop_y, :crop_w, :crop_h)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
	def write_date(date)
	  if date != nil
	    date.to_s
	  else
	    Date.current().to_s
	end       
  end   
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>


  <div class="field">
    <%= f.label :image %>
    <%= image_tag(item.image_url(:thumb).to_s) %> <br>
  </div>

  <div class="field">
    <%= f.label :change_image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="row">
      <div class="col-md-10">
          <div class="form-group">
              <%= f.label :date_lended %>
              <div class='input-group date' id='date_lended'>
                  <input type="text" class="form-control"></input>
                  <span class="input-group-addon">
                      <span class="fa fa-calendar"></span>
                  </span>
              </div>
              <%= f.text_field :date_lended, :hidden => "true" %>
          </div>
      </div>
      <div class='col-md-5'>
          <div class="form-group">
              <%= f.label :initial_return_date %>
              <div class='input-group date' id='initial_return_date'>
                <input type="text" class="form-control"></input>
                  <span class="input-group-addon">
                      <span class="fa fa-calendar"></span>
                  </span>
              </div>
              <%= f.text_field :initial_return_date,  :hidden => "true" %>
          </div>
      </div>
  </div>
  <div class="field">
    <%= f.label :recipient %>
    <% if params[:action] == "edit" %>
      <%= link_to @item.recipient.name, @item.recipient , class: 'form-control',:readonly => true %>
    <% else %>
      <p> <%=t(:is_on_site) %> <span> <%=t(:check_here) %> <%= f.check_box :is_guest , :id => "ck-recipient", :class => "squaredOne" %></span></p> 

      <%= f.text_field :recipient_id, :class=> "form-control user-search" , :placeholder => t(:find_by_username)%>    
      <p><%=t(:is_on_list) %></p>          
      <select id="user-search-results" name="item[recipient_email]" size="5"> </select>
    <% end %>
  </div>

  <div class="row guest">
      <div class='col-md-5'>
          <div class="form-group">
              <%= f.label t(:still_not) %>
              <div class='input-group'>
                  <%= f.text_field :guest_recipient, :class=> "form-control" %>
              </div>
              <%= f.label t(:add_info) %>
              <br/>
              <%= f.label t(:phone_number) %>
              <%= f.text_field :guest_phone,  :class=> 'form-control' %>

              <%= f.label t(:address) %>
              <%= f.text_field :guest_address, :class=> 'form-control' %>

              <%= f.label t(:contact_email) %>
              <%= f.text_field :guest_email, :class=> 'form-control' %>
          </div>
      </div>
  </div>

  <% if params[:action] == "edit" %>
    <div class="row">
          <div class='col-md-5'>
            <span><%= t(:got_back_q) %> <%= f.check_box :returned , :id => "ck-tem-back", :class => "squaredOne" %></span>
              <div class="form-group">
                  <div class='input-group date returned-date-h' id='datetimepicker8'>
                      <%= f.text_field :actual_return_date,:value => Date.current().strftime("%d-%m-%Y"), "data-provide" => 'datepicker', :class=> "form-control" %>
                      <span class="input-group-addon">
                          <span class="fa fa-calendar"></span>
                      </span>
                  </div>
              </div>
          </div>
      </div>
  <% end %>

  <div class="actions" >
    <%= f.submit  class: "btn btn-primary" %>
  </div>

<% end %>

<script type="text/javascript">
    $(function () {
        $('#date_lended').datepicker({endDate: new Date(), 
                                         language: "<%=I18n.locale%>",
                                         todayBtn: true
                                      });
        $('#date_lended').datepicker('setDate', $("#item_date_lended").val());
        $('#initial_return_date').datepicker('setDate', $("#item_initial_return_date").val());

        $('#initial_return_date').datepicker({language: "<%=I18n.locale%>"});
        $('#datetimepicker8').datepicker({
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down",
                next: "fa fa-arrow-right",
                previous: "fa fa-arrow-left"
            }
        });

        $('#date_lended').datepicker().on("input change", function (e) {
          if($('#date_lended').datepicker('getDate')){ 
            $("#item_date_lended").attr("value",$('#date_lended').datepicker('getDate').toISOString().slice(0,10));
            $("#initial_return_date").datepicker("setStartDate", $("#date_lended").datepicker("getDate"));
            $("#initial_return_date").datepicker( "setDate", $("#date_lended").datepicker("getDate"));
          }
        });
        $('#initial_return_date').datepicker().on("input change", function (e) {
          if( $('#initial_return_date').datepicker('getDate')){ 
            $("#item_initial_return_date").attr("value",$('#initial_return_date').datepicker('getDate').toISOString().slice(0,10));
          }
        });

        $('.edit_item').submit(function(e){ 
          if (!isDateISO($("#item_date_lended").attr("value"))){
            $("#item_date_lended").attr("value",$('#date_lended').datepicker('getDate').toISOString().slice(0,10));  
          }

          if (!isDateISO($("#item_initial_return_date").attr("value"))){
            $("#item_initial_return_date").attr("value",$('#initial_return_date').datepicker('getDate').toISOString().slice(0,10));
          }
        });

    });

 function isDateISO(date){
      date = date.split('-');
      if (date.length != 3 )
        return false

      if (date[0].length != 4)
        return false

      if (date[1].length != 2)
        return false

      m = parseInt(date[1]);
      if (m < 0 || m > 11)
        return false

      d = parseInt(date[2]);
      if (d < 0 || d > 31)
        return false

      return true;
 }

</script>

app/views/items/crop.html.erb
Crop Image!

<div id="cropbox"></div>


<%= form_for @item do |f| %>
  <% %w[x y w h].each do |attribute| %>
 	  <%= f.hidden_field "crop_#{attribute}"%>
  <% end %>
  
  <%= f.text_field :initial_return_date,  :hidden => "true" %>
  <%= f.text_field :date_lended,  :hidden => "true" %>
  
 <div class="action">
   <%= f.submit "Crop" %>
 </div>


<% end %>


<script> 

  var basic = $("#cropbox").croppie({
  	viewport: {
        width: 150,
        height: 150,
        type: 'square'
    },
     boundary: {
        width: 600,
        height: 600
    },

    update: function(e){
    	points = e.points;
    	console.log(e.points)
    	$('#item_crop_x').val(points[0])
    	$('#item_crop_y').val(points[1])
    	$('#item_crop_w').val(points[2])
    	$('#item_crop_h').val(points[3])

    }
	});

  basic.croppie('bind', {
  	url: "<%= @item.image_url(:large) %>",
    points: [0,0,600,600],
   
	});


</script>

app/views/items/edit.html.erb
<h1><%= t(:update) %> Item</h1>

<%= render 'form', item: @item %>

<%= link_to t(:show), @item %> |
<%= link_to t(:back), items_path %>

app/views/items/index.html.erb
<% provide(:title, t(:items_list) )%>
<% provide(:subtitle, t(:items_subtitle)) %>

  <div class="row">
    <div class="col-lg-12">
          <div class="add-button-wrapper">
          <%= link_to new_item_path , :class => "btn btn-lg btn-warning" do %>
            <i class="fa fa-plus" aria-hidden="true"></i> <%= t :add %> 
          <% end %>
          </div>
      </div>
  </div>


  <% @items_decorators.each do |item| %>     
  <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title-custom"><i class="fa fa-book"></i>  <%= link_to item.name, item %></h3>
            <h3 class="panel-user-name"><%= t :with %> <i class="fa fa-arrow-right"></i> <%= item.recipient.name %>        <span><%= link_to t(:show), user_path(item.recipient) , :class => "btn btn-xs btn-success" %></span></h3> 

        </div>
       
      <div class="panel-body">
        <div class="list-img-wrapper">
          <%= image_tag(item.image_url(:thumb).to_s, class: 'list-item-img')  %>
        </div>

        <div class="list-info-wrapper">
          <p>
            <strong><%= t :what_is_it %></strong>
            <%= item.description %>.
          </p>

          <p>
            <strong><%= t :when %></strong>
            <%= l(item.date_lended) %>
          </p>
          <p>
            <strong><%= t :return_date %></strong>
            <%= l(item.initial_return_date) %>
          </p>

         <div class="progress">
            <div class="progress-bar <%= item.progress_status  %> progress-bar-success" role="progressbar" 
            aria-valuenow="<%=  item.progress  %>." 
            aria-valuemin="0" 
            aria-valuemax="100" 
            style="width:<%= item.progress %>%;">
            <%= item.progress_message %>  
            </div>
         </div>
          <%= link_to t(:edit), edit_item_path(item.item), :class => "btn btn-sm btn-info" if  item.is_mine?(current_user) %>
          <%= link_to t(:got_back), item_return_path(item.item) , "method" => "post",:class => "btn btn-sm btn-warning" %>
        </div>
      </div>
    </div>    
    <% end %>

app/views/items/new.html.erb
<% provide(:title, t(:new_item) )%>


<h1><%=t(:new_item) %></h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<% provide(:title, @item.name) %>

    <div class="container-fluid">
        <!-- Page Heading -->

        <div class="row">
        	<div class="col-lg-12">
	        	<div class="panel panel-default">
	                <div class="panel-heading">
	                    <h3 class="panel-title"><i class="fa fa-book"></i>  <%= @item.name %></h3>
	                </div>
	                   
					<div class="panel-body">
			    	<p id="notice"><%= notice %></p>
						<p>
						  <strong>O que que é? Como tava?:</strong>
						  <%= @item.description %>. 
						</p>

						<p>
						  <strong>Quando:</strong>
						  <%= @item.date_lended %>
						</p>

						<%= link_to 'Edit  |', edit_item_path(@item) if @item.is_owned_by?(current_user) %>
						<%= link_to 'Back', items_path %>
					</div>
	            </div>		
        	</div>
        </div>
        <!-- /.row -->

        <div class="row">                    
        </div>    <!-- /.row -->
	</div>        <!-- /.container-fluid -->